# Generated by Django 6.0.3 on 2026-04-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("dj_queue", "0001_initial"),
  ]

  operations = [
    migrations.CreateModel(
      name="Pause",
      fields=[
        (
          "id",
          models.BigAutoField(
            auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
          ),
        ),
        ("queue_name", models.CharField(max_length=64, unique=True)),
        ("created_at", models.DateTimeField(auto_now_add=True)),
      ],
      options={
        "db_table": "dj_queue_pauses",
      },
    ),
    migrations.CreateModel(
      name="Semaphore",
      fields=[
        (
          "id",
          models.BigAutoField(
            auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
          ),
        ),
        ("key", models.CharField(max_length=255, unique=True)),
        ("value", models.IntegerField()),
        ("limit", models.IntegerField()),
        ("expires_at", models.DateTimeField()),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
      ],
      options={
        "db_table": "dj_queue_semaphores",
        "indexes": [
          models.Index(fields=["key", "value"], name="dj_queue_se_key_7a5af2_idx"),
          models.Index(fields=["expires_at"], name="dj_queue_se_expires_811b4d_idx"),
        ],
      },
    ),
  ]
