# Generated by Django 6.0.3 on 2026-04-06 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("dj_queue", "0002_pause_semaphore"),
  ]

  operations = [
    migrations.CreateModel(
      name="RecurringTask",
      fields=[
        (
          "id",
          models.BigAutoField(
            auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
          ),
        ),
        ("key", models.CharField(max_length=255, unique=True)),
        ("task_path", models.CharField(max_length=255)),
        ("payload", models.JSONField(blank=True, null=True)),
        ("schedule", models.CharField(max_length=255)),
        ("queue_name", models.CharField(default="default", max_length=64)),
        ("priority", models.SmallIntegerField(default=0)),
        ("description", models.TextField(blank=True, default="")),
        ("static", models.BooleanField(default=False)),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
      ],
      options={
        "db_table": "dj_queue_recurring_tasks",
      },
    ),
    migrations.CreateModel(
      name="RecurringExecution",
      fields=[
        (
          "id",
          models.BigAutoField(
            auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
          ),
        ),
        ("task_key", models.CharField(max_length=255)),
        ("run_at", models.DateTimeField()),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        (
          "job",
          models.OneToOneField(
            blank=True,
            null=True,
            on_delete=django.db.models.deletion.CASCADE,
            related_name="recurring_execution",
            to="dj_queue.job",
          ),
        ),
      ],
      options={
        "db_table": "dj_queue_recurring_executions",
        "indexes": [
          models.Index(fields=["task_key", "run_at"], name="dj_queue_re_task_ke_8e21b4_idx")
        ],
        "constraints": [
          models.UniqueConstraint(
            fields=("task_key", "run_at"),
            name="dj_queue_recurring_executions_task_key_run_at_unique",
          )
        ],
      },
    ),
  ]
