# Generated by Django 6.0.4 on 2026-04-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("dj_queue", "0004_dashboard"),
  ]

  operations = [
    migrations.RemoveConstraint(
      model_name="recurringexecution",
      name="dj_queue_recurring_executions_task_key_run_at_unique",
    ),
    migrations.RemoveIndex(
      model_name="recurringexecution",
      name="dj_queue_re_task_ke_8e21b4_idx",
    ),
    migrations.RenameField(
      model_name="job",
      old_name="backend_name",
      new_name="backend_alias",
    ),
    migrations.AddField(
      model_name="pause",
      name="backend_alias",
      field=models.CharField(default="default", max_length=64),
    ),
    migrations.AddField(
      model_name="process",
      name="backend_alias",
      field=models.CharField(default="default", max_length=64),
    ),
    migrations.AddField(
      model_name="readyexecution",
      name="latency_started_at",
      field=models.DateTimeField(blank=True, null=True),
    ),
    migrations.AddField(
      model_name="recurringexecution",
      name="backend_alias",
      field=models.CharField(default="default", max_length=64),
    ),
    migrations.AddField(
      model_name="recurringtask",
      name="backend_alias",
      field=models.CharField(default="default", max_length=64),
    ),
    migrations.AlterField(
      model_name="pause",
      name="queue_name",
      field=models.CharField(max_length=64),
    ),
    migrations.AlterField(
      model_name="recurringtask",
      name="key",
      field=models.CharField(max_length=255),
    ),
    migrations.AddIndex(
      model_name="pause",
      index=models.Index(
        fields=["backend_alias", "queue_name"], name="dj_queue_pa_backend_fa28ca_idx"
      ),
    ),
    migrations.AddIndex(
      model_name="process",
      index=models.Index(fields=["backend_alias"], name="dj_queue_pr_backend_22fe17_idx"),
    ),
    migrations.AddIndex(
      model_name="recurringexecution",
      index=models.Index(
        fields=["backend_alias", "task_key", "run_at"], name="dj_queue_re_backend_ccabe5_idx"
      ),
    ),
    migrations.AddIndex(
      model_name="recurringtask",
      index=models.Index(fields=["backend_alias", "key"], name="dj_queue_re_backend_26686e_idx"),
    ),
    migrations.AddConstraint(
      model_name="pause",
      constraint=models.UniqueConstraint(
        fields=("backend_alias", "queue_name"),
        name="dj_queue_pauses_backend_alias_queue_name_unique",
      ),
    ),
    migrations.AddConstraint(
      model_name="recurringexecution",
      constraint=models.UniqueConstraint(
        fields=("backend_alias", "task_key", "run_at"),
        name="dj_queue_recur_exec_backend_run_at_unique",
      ),
    ),
    migrations.AddConstraint(
      model_name="recurringtask",
      constraint=models.UniqueConstraint(
        fields=("backend_alias", "key"), name="dj_queue_recurring_tasks_backend_alias_key_unique"
      ),
    ),
  ]
