# Generated by Django 6.0.4 on 2026-05-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    (
      "dj_queue",
      "0005_remove_recurringexecution_dj_queue_recurring_executions_task_key_run_at_unique_and_more",
    ),
  ]

  operations = [
    migrations.AddIndex(
      model_name="blockedexecution",
      index=models.Index(
        fields=["concurrency_key", "-priority", "id"], name="dj_queue_bl_concurr_2d8393_idx"
      ),
    ),
    migrations.AddIndex(
      model_name="blockedexecution",
      index=models.Index(
        fields=["expires_at", "-priority", "id"], name="dj_queue_bl_expires_f4b090_idx"
      ),
    ),
    migrations.AddIndex(
      model_name="failedexecution",
      index=models.Index(fields=["created_at", "job"], name="dj_queue_fa_created_343d7d_idx"),
    ),
    migrations.AddIndex(
      model_name="job",
      index=models.Index(
        fields=["backend_alias", "finished_at", "id"], name="dj_queue_jo_backend_ee105e_idx"
      ),
    ),
    migrations.AddIndex(
      model_name="readyexecution",
      index=models.Index(fields=["-priority", "id"], name="dj_queue_re_priorit_ee6ffe_idx"),
    ),
    migrations.AddIndex(
      model_name="readyexecution",
      index=models.Index(
        fields=["queue_name", "-priority", "id"], name="dj_queue_re_queue_n_612755_idx"
      ),
    ),
    migrations.AddIndex(
      model_name="recurringexecution",
      index=models.Index(
        fields=["backend_alias", "run_at", "id"], name="dj_queue_re_backend_a68bf1_idx"
      ),
    ),
    migrations.AddIndex(
      model_name="scheduledexecution",
      index=models.Index(
        fields=["scheduled_at", "-priority", "id"], name="dj_queue_sc_schedul_edba95_idx"
      ),
    ),
  ]
