# Generated by Django 6.0.4 on 2026-05-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("dj_queue", "0006_blockedexecution_dj_queue_bl_concurr_2d8393_idx_and_more"),
  ]

  operations = [
    migrations.AddField(
      model_name="recurringtask",
      name="next_run_at",
      field=models.DateTimeField(blank=True, null=True),
    ),
    migrations.AddIndex(
      model_name="recurringtask",
      index=models.Index(
        fields=["backend_alias", "next_run_at", "key"], name="dj_queue_rt_next_run_idx"
      ),
    ),
  ]
