# Generated by Django 6.0.5 on 2026-05-09 10:31

from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def backfill_execution_backend_alias(apps, schema_editor):
  job_model = apps.get_model("dj_queue", "Job")
  for model_name in ("ReadyExecution", "ScheduledExecution", "BlockedExecution"):
    state_model = apps.get_model("dj_queue", model_name)
    state_model.objects.using(schema_editor.connection.alias).update(
      backend_alias=Subquery(
        job_model.objects.using(schema_editor.connection.alias)
        .filter(pk=OuterRef("job_id"))
        .values("backend_alias")[:1]
      )
    )


class Migration(migrations.Migration):
  dependencies = [
    ("dj_queue", "0007_recurringtask_next_run_at"),
  ]

  operations = [
    migrations.RemoveIndex(
      model_name="blockedexecution",
      name="dj_queue_bl_concurr_1ce730_idx",
    ),
    migrations.RemoveIndex(
      model_name="blockedexecution",
      name="dj_queue_bl_expires_ea27f7_idx",
    ),
    migrations.RemoveIndex(
      model_name="blockedexecution",
      name="dj_queue_bl_concurr_2d8393_idx",
    ),
    migrations.RemoveIndex(
      model_name="blockedexecution",
      name="dj_queue_bl_expires_f4b090_idx",
    ),
    migrations.RemoveIndex(
      model_name="readyexecution",
      name="dj_queue_re_priorit_bfc737_idx",
    ),
    migrations.RemoveIndex(
      model_name="readyexecution",
      name="dj_queue_re_queue_n_9931e4_idx",
    ),
    migrations.RemoveIndex(
      model_name="readyexecution",
      name="dj_queue_re_priorit_ee6ffe_idx",
    ),
    migrations.RemoveIndex(
      model_name="readyexecution",
      name="dj_queue_re_queue_n_612755_idx",
    ),
    migrations.RemoveIndex(
      model_name="scheduledexecution",
      name="dj_queue_sc_schedul_7e8dd0_idx",
    ),
    migrations.RemoveIndex(
      model_name="scheduledexecution",
      name="dj_queue_sc_schedul_edba95_idx",
    ),
    migrations.AddField(
      model_name="blockedexecution",
      name="backend_alias",
      field=models.CharField(max_length=64, null=True),
    ),
    migrations.AddField(
      model_name="readyexecution",
      name="backend_alias",
      field=models.CharField(max_length=64, null=True),
    ),
    migrations.AddField(
      model_name="scheduledexecution",
      name="backend_alias",
      field=models.CharField(max_length=64, null=True),
    ),
    migrations.RunPython(backfill_execution_backend_alias, migrations.RunPython.noop),
    migrations.AlterField(
      model_name="blockedexecution",
      name="backend_alias",
      field=models.CharField(max_length=64),
    ),
    migrations.AlterField(
      model_name="readyexecution",
      name="backend_alias",
      field=models.CharField(max_length=64),
    ),
    migrations.AlterField(
      model_name="scheduledexecution",
      name="backend_alias",
      field=models.CharField(max_length=64),
    ),
    migrations.AddIndex(
      model_name="blockedexecution",
      index=models.Index(
        fields=["backend_alias", "concurrency_key", "priority", "id"],
        name="dj_queue_bl_backend_conc_idx",
      ),
    ),
    migrations.AddIndex(
      model_name="blockedexecution",
      index=models.Index(
        fields=["backend_alias", "expires_at", "concurrency_key"],
        name="dj_queue_bl_backend_exp_conc_idx",
      ),
    ),
    migrations.AddIndex(
      model_name="blockedexecution",
      index=models.Index(
        fields=["backend_alias", "concurrency_key", "-priority", "id"],
        name="dj_queue_bl_backend_conc_desc_idx",
      ),
    ),
    migrations.AddIndex(
      model_name="blockedexecution",
      index=models.Index(
        fields=["backend_alias", "expires_at", "-priority", "id"],
        name="dj_queue_bl_backend_exp_desc_idx",
      ),
    ),
    migrations.AddIndex(
      model_name="readyexecution",
      index=models.Index(
        fields=["backend_alias", "priority", "id"], name="dj_queue_re_backend_prio_idx"
      ),
    ),
    migrations.AddIndex(
      model_name="readyexecution",
      index=models.Index(
        fields=["backend_alias", "queue_name", "priority", "id"],
        name="dj_queue_re_backend_queue_idx",
      ),
    ),
    migrations.AddIndex(
      model_name="readyexecution",
      index=models.Index(
        fields=["backend_alias", "-priority", "id"], name="dj_queue_re_backend_prio_desc_idx"
      ),
    ),
    migrations.AddIndex(
      model_name="readyexecution",
      index=models.Index(
        fields=["backend_alias", "queue_name", "-priority", "id"],
        name="dj_queue_re_backend_queue_desc_idx",
      ),
    ),
    migrations.AddIndex(
      model_name="scheduledexecution",
      index=models.Index(
        fields=["backend_alias", "scheduled_at", "priority", "id"],
        name="dj_queue_se_backend_due_idx",
      ),
    ),
    migrations.AddIndex(
      model_name="scheduledexecution",
      index=models.Index(
        fields=["backend_alias", "scheduled_at", "-priority", "id"],
        name="dj_queue_se_backend_due_desc_idx",
      ),
    ),
  ]
