# Generated by Django 6.0.5 on 2026-05-22 11:40

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("dj_queue", "0008_remove_blockedexecution_dj_queue_bl_concurr_1ce730_idx_and_more"),
  ]

  operations = [
    migrations.RemoveConstraint(
      model_name="process",
      name="dj_queue_processes_name_supervisor_unique",
    ),
    migrations.AddField(
      model_name="process",
      name="supervisor_identity",
      field=models.GeneratedField(
        db_persist=True,
        expression=django.db.models.functions.comparison.Coalesce(
          "supervisor_id",
          models.Value(0, output_field=models.BigIntegerField()),
          output_field=models.BigIntegerField(),
        ),
        output_field=models.BigIntegerField(),
      ),
    ),
    migrations.AddConstraint(
      model_name="process",
      constraint=models.UniqueConstraint(
        fields=("name", "supervisor_identity"), name="djq_pr_name_parent_uniq"
      ),
    ),
  ]
