# Generated by Django 6.0.5 on 2026-05-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("dj_queue", "0009_remove_process_dj_queue_processes_name_supervisor_unique_and_more"),
  ]

  operations = [
    migrations.RemoveConstraint(
      model_name="process",
      name="djq_pr_name_parent_uniq",
    ),
    migrations.AddConstraint(
      model_name="process",
      constraint=models.UniqueConstraint(
        fields=("backend_alias", "name", "supervisor_identity"),
        name="djq_pr_backend_name_parent_uniq",
      ),
    ),
  ]
