# Generated by Django 6.0.5 on 2026-05-26 22:21

from django.db import migrations


class Migration(migrations.Migration):
  dependencies = [
    ("dj_queue", "0010_remove_process_djq_pr_name_parent_uniq_and_more"),
  ]

  operations = [
    migrations.RemoveIndex(
      model_name="blockedexecution",
      name="djq_bl_b_conc_idx",
    ),
    migrations.RemoveIndex(
      model_name="blockedexecution",
      name="djq_bl_b_exp_conc_idx",
    ),
    migrations.RemoveIndex(
      model_name="readyexecution",
      name="djq_re_b_prio_idx",
    ),
    migrations.RemoveIndex(
      model_name="readyexecution",
      name="djq_re_b_queue_idx",
    ),
    migrations.RemoveIndex(
      model_name="scheduledexecution",
      name="djq_se_b_due_idx",
    ),
  ]
