# Generated by Django 6.0.5 on 2026-06-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("dj_queue", "0011_remove_blockedexecution_djq_bl_b_conc_idx_and_more"),
  ]

  operations = [
    migrations.AddIndex(
      model_name="job",
      index=models.Index(
        fields=["backend_alias", "queue_name", "id"],
        name="djq_jobs_b_queue_id_idx",
      ),
    ),
    migrations.AddIndex(
      model_name="job",
      index=models.Index(
        fields=["backend_alias", "concurrency_key"],
        name="djq_jobs_b_conc_idx",
      ),
    ),
    migrations.AddIndex(
      model_name="process",
      index=models.Index(
        fields=["backend_alias", "last_heartbeat_at", "id"],
        name="djq_pr_b_heart_id_idx",
      ),
    ),
  ]
