# Generated by Django 6.0.5 on 2026-06-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("dj_queue", "0012_job_djq_jobs_b_queue_id_idx_job_djq_jobs_b_conc_idx_and_more"),
  ]

  operations = [
    migrations.AddField(
      model_name="failedexecution",
      name="retry_at",
      field=models.DateTimeField(blank=True, null=True),
    ),
    migrations.AddIndex(
      model_name="failedexecution",
      index=models.Index(fields=["retry_at", "job"], name="dj_queue_fa_retry_a_2ff769_idx"),
    ),
  ]
