# Generated by Django 6.0.8 on 2026-09-02 05:52
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("dj_queue", "0013_failedexecution_retry_at_and_more"),
  ]

  operations = [
    migrations.AddField(
      model_name="semaphore",
      name="active_count",
      field=models.IntegerField(null=True),
    ),
  ]
