# Generated by Django 6.0.8 on 2026-09-02 06:14
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("dj_queue", "0014_semaphore_active_count"),
  ]

  operations = [
    migrations.AddField(
      model_name="job",
      name="concurrency_duration",
      field=models.IntegerField(blank=True, null=True),
    ),
  ]
