# Generated by Django 6.0.8 on 2026-09-02 06:43
# ruff: noqa: RUF012

import uuid

from django.db import migrations, models
from django.db.models import F


def backfill_intended_job_id(apps, schema_editor):
  RecurringExecution = apps.get_model("dj_queue", "RecurringExecution")
  executions = RecurringExecution.objects.using(schema_editor.connection.alias)
  executions.filter(job__isnull=False).update(intended_job_id=F("job_id"))

  while True:
    pending = list(executions.filter(intended_job_id__isnull=True).order_by("pk")[:1000])
    if not pending:
      break
    for execution in pending:
      execution.intended_job_id = uuid.uuid4()
    executions.bulk_update(pending, ["intended_job_id"], batch_size=1000)


class Migration(migrations.Migration):
  dependencies = [
    ("dj_queue", "0015_job_concurrency_policy"),
  ]

  operations = [
    migrations.AddField(
      model_name="recurringexecution",
      name="intended_job_id",
      field=models.UUIDField(null=True),
    ),
    migrations.RunPython(backfill_intended_job_id, migrations.RunPython.noop),
    migrations.AlterField(
      model_name="recurringexecution",
      name="intended_job_id",
      field=models.UUIDField(default=uuid.uuid4),
    ),
    migrations.AddConstraint(
      model_name="recurringexecution",
      constraint=models.CheckConstraint(
        condition=models.Q(
          ("job__isnull", True),
          ("job", models.F("intended_job_id")),
          _connector="OR",
        ),
        name="djq_re_job_matches_intended",
      ),
    ),
  ]
