# Generated by Django 6.0.8 on 2026-09-02 06:14
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("dj_queue", "0016_job_concurrency_limit"),
  ]

  operations = [
    migrations.AddField(
      model_name="job",
      name="concurrency_on_conflict",
      field=models.CharField(blank=True, max_length=7, null=True),
    ),
  ]
