# Generated by Django 6.0.8 on 2026-09-02 06:14
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("dj_queue", "0017_job_concurrency_on_conflict"),
  ]

  operations = [
    migrations.AddConstraint(
      model_name="job",
      constraint=models.CheckConstraint(
        condition=models.Q(
          models.Q(
            ("concurrency_duration__isnull", True),
            ("concurrency_limit__isnull", True),
            ("concurrency_on_conflict__isnull", True),
          ),
          models.Q(
            ("concurrency_duration__gte", 1),
            ("concurrency_duration__isnull", False),
            ("concurrency_key__isnull", False),
            ("concurrency_limit__gte", 1),
            ("concurrency_limit__isnull", False),
            ("concurrency_on_conflict__in", ("block", "discard")),
            ("concurrency_on_conflict__isnull", False),
            models.Q(("concurrency_key", ""), _negated=True),
          ),
          _connector="OR",
        ),
        name="djq_jobs_concurrency_policy",
      ),
    ),
  ]
