# Generated by Django 6.0.8 on 2026-09-02 06:43
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("dj_queue", "0018_job_concurrency_policy"),
  ]

  operations = [
    migrations.AddField(
      model_name="recurringexecution",
      name="intended_job_id",
      field=models.UUIDField(null=True),
    ),
  ]
